Msgs:
  geometry:
    {
    Accel: Accel.h,
    AccelStamped: AccelStamped.h,
    AccelWithCovariance: AccelWithCovariance.h,
    AccelWithCovarianceStamped: AccelWithCovarianceStamped.h,
    Inertia: Inertia.h,
    InertiaStamped: InertiaStamped.h,
    Point32: Point32.h,
    Point: Point.h,
    PointStamped: PointStamped.h,
    Polygon: Polygon.h,
    PolygonStamped: PolygonStamped.h,
    Pose2D: Pose2D.h,
    PoseArray: PoseArray.h,
    Pose: Pose.h,
    PoseStamped: PoseStamped.h,
    PosewithCovariance: PoseWithCovariance.h,
    PoseWithCovarianceStamped: PoseWithCovarianceStamped.h,
    Quarternion: Quaternion.h,
    QuarternionStamped: QuaternionStamped.h,
    Transform: Transform.h,
    TransformStamped: TransformStamped.h,
    Twist: Twist.h,
    TwistStamped: TwistStamped.h,
    TwistWithCovariance: TwistWithCovariance.h,
    TwistWithCovarianceStamped: TwistWithCovarianceStamped.h,
    Vector3: Vector3.h,
    Vector3Stamped: Vector3Stamped.h,
    Wrench: Wrench.h,
    WrenchStamped: WrenchStamped.h
    }